# This file contains values from Cookiecutter

default_context:
  project_name: "ControlNet"
  repo_name: "controlnet"
  description: "ControlNet to generate medical images"
  organization: "None"
  license: "No license"
  organization_email: "none@none.pt"
  line_length: "120"
  python_minimal_version: "3.9"
