site_name: controlnet
site_description: ControlNet to generate medical images
site_author: Francisco Caetano

#repo_url:

theme:
    name: 'material'
    locale: en
    font: false

nav:
    - Home: index.md

# WIP
#markdown_extensions:
#  - mkautodoc
#plugins:
#  - mkdocs-jupyter
